services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: nexaai-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9112112918
      POSTGRES_DB: nexaai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: